### PR TITLE
ci(renovate): update shared renovate config

### PR DESCRIPTION
**Pull request by ghost**
This changes the renovate settings to what we've been using for the aggregate-data-entry app. It's slightly different than what we had configured originally. The difference is that I've taken a more conservative approach, and stuck closer to the renovate defaults. I can imagine that after further experimentation we'd slowly start introducing some more experimental features, but for now this seemed more practical.

Also some of the explicit configuration that has been removed was already in the renovate defaults or config groups that we were using. A short summary of what this config does:

- Base config: https://docs.renovatebot.com/presets-config/#configbase
- Automerge minor and patch updates ([if they pass CI](https://docs.renovatebot.com/presets-default/#automergerequireallstatuschecks))
- Automerge through a PR (more noisy than through a branch, but slightly safer)
- [Enable vulnerability alerts](https://docs.renovatebot.com/presets-default/#enablevulnerabilityalerts)
- Only merge updates that are past the npm unpublish window
- Run outside of Oslo office hours
- Require manual approval for creating PRs for major updates
- https://docs.renovatebot.com/config-presets

This config can be used by adding the following to a repo's `.github/renovate.json` (or [another location](https://docs.renovatebot.com/configuration-options/)):

```
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "extends": ["local>dhis2/.github:renovate-config"]
}
```

[Only cli-style seems to be using this shared config](https://github.com/search?q=org%3Adhis2++filename%3Arenovate.json&type=Code&ref=advsearch&l=&l=), but it doesn't seem to be active yet.

### CODE REVIEW

**Review by kabaros — APPROVED** [review]
looks reasonable to me .. maybe someone with more experience should have a look too though

**Review by Birkbjo — APPROVED** [review]

**Comment by ghost** [comment]
@amcgee I've moved the configuration here: https://github.com/dhis2/renovate-config. For the others, Austin and I talked about it on slack [here](https://dhis2.slack.com/archives/CJF3MDK8Q/p1671024280802589).

So this PR now removes the preset from this repo. The preset has already been added to the other repo. After this I'll enable the preset for the aggregate-data-entry-app (and maintenance-app-beta, once that is possible).

Btw. Austin, I couldn't enable branch protection for main for the other repo. Seems I don't have permission for that. Other than that the settings on that repo should be good.

**Comment by ghost** [comment]
@amcgee Could you take a look at this? I'll need your permission in order to merge this. All it does is remove the config from this repo (see above comment).

**Review by amcgee — APPROVED** [review]

**Comment by ghost** [comment]
Thanks @amcgee!

**Pull request merged**
